// Jenkinsfile (Scripted Pipeline)
def remote = [:]
    remote.name = 'pi'
    remote.host = "${IP}"
    remote.user = 'pi'
    remote.allowAnyHosts = true

node {
    stage('update') {
		withCredentials([sshUserPrivateKey(credentialsId: "jenkins-go", keyFileVariable: 'keyfile')]) {
			remote.identityFile = keyFile
			sshCommand remote: remote, dryRun: false, command: """
				sudo apt-get update -y
				sudo apt-get upgrade -y
				"""
		}
	}
		
    stage('microsoft prod') {

		withCredentials([sshUserPrivateKey(credentialsId: "jenkins-go", keyFileVariable: 'keyfile')]) {
			remote.identityFile = keyFile
			sshCommand remote: remote, dryRun: false, command: """
				sudo apt-get install -y wget 
                sudo apt-get update -y
                sudo apt-get install -y apt-transport-https 
                sudo apt-get install -y vim 
                sudo apt-get install -y curl 
                sudo apt-get install -y git

			"""
		}
    }
    stage('dotnet-sdk-3.1') {

		withCredentials([sshUserPrivateKey(credentialsId: "jenkins-go", keyFileVariable: 'keyfile')]) {
			remote.identityFile = keyFile
			sshCommand remote: remote, dryRun: false, command: """
                sudo apt-get update -y
				wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
				wget https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-3.1.415-linux-arm32-binaries
                sudo mkdir -p $HOME/dotnet
                mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.1.415-linux-arm.tar.gz -C $HOME/dotnet
                export DOTNET_ROOT=$HOME/dotnet
                export PATH=$PATH:$HOME/dotnet

			"""
		}
    }
    stage('jetkins repo')
    {
        withCredentials([sshUserPrivateKey(credentialsId: "jenkins-go", keyFileVariable: 'keyfile')]) {
            remote.identityFile = keyFile
            sshCommand remote: remote, dryRun: false, command: """
                apt install gnupg2 -y
                sudo apt-get install openjdk-8-jre -y
            """
        }
    }    
}
